// Comprehensive list of countries and nationalities with multilingual support (EN, AR, TR)
export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", nameTr: "Afganistan", nationality: "Afghan", nationalityAr: "أفغاني", nationalityTr: "Afgan" },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", nameTr: "Arnavutluk", nationality: "Albanian", nationalityAr: "ألباني", nationalityTr: "Arnavut" },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", nameTr: "Cezayir", nationality: "Algerian", nationalityAr: "جزائري", nationalityTr: "Cezayirli" },
  { code: "AD", name: "Andorra", nameAr: "أندورا", nameTr: "Andorra", nationality: "Andorran", nationalityAr: "أندوري", nationalityTr: "Andorralı" },
  { code: "AO", name: "Angola", nameAr: "أنغولا", nameTr: "Angola", nationality: "Angolan", nationalityAr: "أنغولي", nationalityTr: "Angolalı" },
  { code: "AG", name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا", nameTr: "Antigua ve Barbuda", nationality: "Antiguan", nationalityAr: "أنتيغوي", nationalityTr: "Antigubalı" },
  { code: "AR", name: "Argentina", nameAr: "الأرجنتين", nameTr: "Arjantin", nationality: "Argentine", nationalityAr: "أرجنتيني", nationalityTr: "Arjantinli" },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", nameTr: "Ermenistan", nationality: "Armenian", nationalityAr: "أرمني", nationalityTr: "Ermeni" },
  { code: "AU", name: "Australia", nameAr: "أستراليا", nameTr: "Avustralya", nationality: "Australian", nationalityAr: "أسترالي", nationalityTr: "Avustralyalı" },
  { code: "AT", name: "Austria", nameAr: "النمسا", nameTr: "Avusturya", nationality: "Austrian", nationalityAr: "نمساوي", nationalityTr: "Avusturyalı" },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", nameTr: "Azerbaycan", nationality: "Azerbaijani", nationalityAr: "أذربيجاني", nationalityTr: "Azerbaycanlı" },
  { code: "BS", name: "Bahamas", nameAr: "جزر البهاما", nameTr: "Bahamalar", nationality: "Bahamian", nationalityAr: "بهامي", nationalityTr: "Bahamalı" },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", nameTr: "Bahreyn", nationality: "Bahraini", nationalityAr: "بحريني", nationalityTr: "Bahreynli" },
  { code: "BD", name: "Bangladesh", nameAr: "بنغلاديش", nameTr: "Bangladeş", nationality: "Bangladeshi", nationalityAr: "بنغلاديشي", nationalityTr: "Bangladeşli" },
  { code: "BB", name: "Barbados", nameAr: "بربادوس", nameTr: "Barbados", nationality: "Barbadian", nationalityAr: "بربادوسي", nationalityTr: "Barbadoslu" },
  { code: "BY", name: "Belarus", nameAr: "بيلاروسيا", nameTr: "Belarus", nationality: "Belarusian", nationalityAr: "بيلاروسي", nationalityTr: "Belaruslu" },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", nameTr: "Belçika", nationality: "Belgian", nationalityAr: "بلجيكي", nationalityTr: "Belçikalı" },
  { code: "BZ", name: "Belize", nameAr: "بليز", nameTr: "Belize", nationality: "Belizean", nationalityAr: "بليزي", nationalityTr: "Belizeli" },
  { code: "BJ", name: "Benin", nameAr: "بنين", nameTr: "Benin", nationality: "Beninese", nationalityAr: "بنيني", nationalityTr: "Beninli" },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", nameTr: "Butan", nationality: "Bhutanese", nationalityAr: "بوتاني", nationalityTr: "Butanlı" },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", nameTr: "Bolivya", nationality: "Bolivian", nationalityAr: "بوليفي", nationalityTr: "Bolivyalı" },
  { code: "BA", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", nameTr: "Bosna-Hersek", nationality: "Bosnian", nationalityAr: "بوسني", nationalityTr: "Bosnalı" },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", nameTr: "Botsvana", nationality: "Motswana", nationalityAr: "بوتسواني", nationalityTr: "Botsvanali" },
  { code: "BR", name: "Brazil", nameAr: "البرازيل", nameTr: "Brezilya", nationality: "Brazilian", nationalityAr: "برازيلي", nationalityTr: "Brezilyalı" },
  { code: "BN", name: "Brunei", nameAr: "بروناي", nameTr: "Brunei", nationality: "Bruneian", nationalityAr: "بروناوي", nationalityTr: "Bruneili" },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", nameTr: "Bulgaristan", nationality: "Bulgarian", nationalityAr: "بلغاري", nationalityTr: "Bulgar" },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", nameTr: "Burkina Faso", nationality: "Burkinabé", nationalityAr: "بوركيني", nationalityTr: "Burkina Fasolu" },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", nameTr: "Burundi", nationality: "Burundian", nationalityAr: "بوروندي", nationalityTr: "Burundili" },
  { code: "CV", name: "Cabo Verde", nameAr: "الرأس الأخضر", nameTr: "Cabo Verde", nationality: "Cape Verdean", nationalityAr: "رأس أخضري", nationalityTr: "Cabo Verdeli" },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", nameTr: "Kamboçya", nationality: "Cambodian", nationalityAr: "كمبودي", nationalityTr: "Kamboçyalı" },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", nameTr: "Kamerun", nationality: "Cameroonian", nationalityAr: "كاميروني", nationalityTr: "Kamerunlu" },
  { code: "CA", name: "Canada", nameAr: "كندا", nameTr: "Kanada", nationality: "Canadian", nationalityAr: "كندي", nationalityTr: "Kanadalı" },
  { code: "CF", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", nameTr: "Orta Afrika Cumhuriyeti", nationality: "Central African", nationalityAr: "أفريقي أوسطي", nationalityTr: "Orta Afrikalı" },
  { code: "TD", name: "Chad", nameAr: "تشاد", nameTr: "Çad", nationality: "Chadian", nationalityAr: "تشادي", nationalityTr: "Çadlı" },
  { code: "CL", name: "Chile", nameAr: "تشيلي", nameTr: "Şili", nationality: "Chilean", nationalityAr: "تشيلي", nationalityTr: "Şilili" },
  { code: "CN", name: "China", nameAr: "الصين", nameTr: "Çin", nationality: "Chinese", nationalityAr: "صيني", nationalityTr: "Çinli" },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", nameTr: "Kolombiya", nationality: "Colombian", nationalityAr: "كولومبي", nationalityTr: "Kolombiyalı" },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", nameTr: "Komorlar", nationality: "Comorian", nationalityAr: "قمري", nationalityTr: "Komorlu" },
  { code: "CG", name: "Congo", nameAr: "الكونغو", nameTr: "Kongo", nationality: "Congolese", nationalityAr: "كونغولي", nationalityTr: "Kongolu" },
  { code: "CD", name: "Congo (DRC)", nameAr: "جمهورية الكونغو الديمقراطية", nameTr: "Demokratik Kongo Cumhuriyeti", nationality: "Congolese", nationalityAr: "كونغولي", nationalityTr: "Kongolu" },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", nameTr: "Kosta Rika", nationality: "Costa Rican", nationalityAr: "كوستاريكي", nationalityTr: "Kosta Rikalı" },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", nameTr: "Hırvatistan", nationality: "Croatian", nationalityAr: "كرواتي", nationalityTr: "Hırvat" },
  { code: "CU", name: "Cuba", nameAr: "كوبا", nameTr: "Küba", nationality: "Cuban", nationalityAr: "كوبي", nationalityTr: "Kübalı" },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", nameTr: "Kıbrıs", nationality: "Cypriot", nationalityAr: "قبرصي", nationalityTr: "Kıbrıslı" },
  { code: "CZ", name: "Czech Republic", nameAr: "جمهورية التشيك", nameTr: "Çek Cumhuriyeti", nationality: "Czech", nationalityAr: "تشيكي", nationalityTr: "Çek" },
  { code: "DK", name: "Denmark", nameAr: "الدنمارك", nameTr: "Danimarka", nationality: "Danish", nationalityAr: "دنماركي", nationalityTr: "Danimarkalı" },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", nameTr: "Cibuti", nationality: "Djiboutian", nationalityAr: "جيبوتي", nationalityTr: "Cibutili" },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", nameTr: "Dominika", nationality: "Dominican", nationalityAr: "دومينيكي", nationalityTr: "Dominikalı" },
  { code: "DO", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", nameTr: "Dominik Cumhuriyeti", nationality: "Dominican", nationalityAr: "دومينيكاني", nationalityTr: "Dominikli" },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", nameTr: "Ekvador", nationality: "Ecuadorian", nationalityAr: "إكوادوري", nationalityTr: "Ekvadorlu" },
  { code: "EG", name: "Egypt", nameAr: "مصر", nameTr: "Mısır", nationality: "Egyptian", nationalityAr: "مصري", nationalityTr: "Mısırlı" },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", nameTr: "El Salvador", nationality: "Salvadoran", nationalityAr: "سلفادوري", nationalityTr: "Salvadorlu" },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", nameTr: "Ekvator Ginesi", nationality: "Equatoguinean", nationalityAr: "غيني استوائي", nationalityTr: "Ekvator Gineli" },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", nameTr: "Eritre", nationality: "Eritrean", nationalityAr: "إريتري", nationalityTr: "Eritreli" },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", nameTr: "Estonya", nationality: "Estonian", nationalityAr: "إستوني", nationalityTr: "Estonyalı" },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", nameTr: "Esvatini", nationality: "Swazi", nationalityAr: "سوازي", nationalityTr: "Svazilandlı" },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", nameTr: "Etiyopya", nationality: "Ethiopian", nationalityAr: "إثيوبي", nationalityTr: "Etiyopyalı" },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", nameTr: "Fiji", nationality: "Fijian", nationalityAr: "فيجي", nationalityTr: "Fijili" },
  { code: "FI", name: "Finland", nameAr: "فنلندا", nameTr: "Finlandiya", nationality: "Finnish", nationalityAr: "فنلندي", nationalityTr: "Finlandiyalı" },
  { code: "FR", name: "France", nameAr: "فرنسا", nameTr: "Fransa", nationality: "French", nationalityAr: "فرنسي", nationalityTr: "Fransız" },
  { code: "GA", name: "Gabon", nameAr: "الغابون", nameTr: "Gabon", nationality: "Gabonese", nationalityAr: "غابوني", nationalityTr: "Gabonlu" },
  { code: "GM", name: "Gambia", nameAr: "غامبيا", nameTr: "Gambiya", nationality: "Gambian", nationalityAr: "غامبي", nationalityTr: "Gambiyalı" },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", nameTr: "Gürcistan", nationality: "Georgian", nationalityAr: "جورجي", nationalityTr: "Gürcü" },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", nameTr: "Almanya", nationality: "German", nationalityAr: "ألماني", nationalityTr: "Alman" },
  { code: "GH", name: "Ghana", nameAr: "غانا", nameTr: "Gana", nationality: "Ghanaian", nationalityAr: "غاني", nationalityTr: "Ganalı" },
  { code: "GR", name: "Greece", nameAr: "اليونان", nameTr: "Yunanistan", nationality: "Greek", nationalityAr: "يوناني", nationalityTr: "Yunan" },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", nameTr: "Grenada", nationality: "Grenadian", nationalityAr: "غريناداوي", nationalityTr: "Grenadalı" },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", nameTr: "Guatemala", nationality: "Guatemalan", nationalityAr: "غواتيمالي", nationalityTr: "Guatemalalı" },
  { code: "GN", name: "Guinea", nameAr: "غينيا", nameTr: "Gine", nationality: "Guinean", nationalityAr: "غيني", nationalityTr: "Gineli" },
  { code: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو", nameTr: "Gine-Bissau", nationality: "Bissau-Guinean", nationalityAr: "غيني بيساوي", nationalityTr: "Gine-Bissaulu" },
  { code: "GY", name: "Guyana", nameAr: "غيانا", nameTr: "Guyana", nationality: "Guyanese", nationalityAr: "غياني", nationalityTr: "Guyanali" },
  { code: "HT", name: "Haiti", nameAr: "هايتي", nameTr: "Haiti", nationality: "Haitian", nationalityAr: "هايتي", nationalityTr: "Haitili" },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", nameTr: "Honduras", nationality: "Honduran", nationalityAr: "هندوراسي", nationalityTr: "Honduraslı" },
  { code: "HU", name: "Hungary", nameAr: "المجر", nameTr: "Macaristan", nationality: "Hungarian", nationalityAr: "مجري", nationalityTr: "Macar" },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", nameTr: "İzlanda", nationality: "Icelandic", nationalityAr: "آيسلندي", nationalityTr: "İzlandalı" },
  { code: "IN", name: "India", nameAr: "الهند", nameTr: "Hindistan", nationality: "Indian", nationalityAr: "هندي", nationalityTr: "Hintli" },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", nameTr: "Endonezya", nationality: "Indonesian", nationalityAr: "إندونيسي", nationalityTr: "Endonezyalı" },
  { code: "IR", name: "Iran", nameAr: "إيران", nameTr: "İran", nationality: "Iranian", nationalityAr: "إيراني", nationalityTr: "İranlı" },
  { code: "IQ", name: "Iraq", nameAr: "العراق", nameTr: "Irak", nationality: "Iraqi", nationalityAr: "عراقي", nationalityTr: "Iraklı" },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", nameTr: "İrlanda", nationality: "Irish", nationalityAr: "أيرلندي", nationalityTr: "İrlandalı" },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", nameTr: "İsrail", nationality: "Israeli", nationalityAr: "إسرائيلي", nationalityTr: "İsrailli" },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", nameTr: "İtalya", nationality: "Italian", nationalityAr: "إيطالي", nationalityTr: "İtalyan" },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", nameTr: "Jamaika", nationality: "Jamaican", nationalityAr: "جامايكي", nationalityTr: "Jamaikalı" },
  { code: "JP", name: "Japan", nameAr: "اليابان", nameTr: "Japonya", nationality: "Japanese", nationalityAr: "ياباني", nationalityTr: "Japon" },
  { code: "JO", name: "Jordan", nameAr: "الأردن", nameTr: "Ürdün", nationality: "Jordanian", nationalityAr: "أردني", nationalityTr: "Ürdünlü" },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", nameTr: "Kazakistan", nationality: "Kazakhstani", nationalityAr: "كازاخستاني", nationalityTr: "Kazak" },
  { code: "KE", name: "Kenya", nameAr: "كينيا", nameTr: "Kenya", nationality: "Kenyan", nationalityAr: "كيني", nationalityTr: "Kenyalı" },
  { code: "KI", name: "Kiribati", nameAr: "كيريباتي", nameTr: "Kiribati", nationality: "I-Kiribati", nationalityAr: "كيريباتي", nationalityTr: "Kiribatili" },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", nameTr: "Kuveyt", nationality: "Kuwaiti", nationalityAr: "كويتي", nationalityTr: "Kuveytli" },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان", nameTr: "Kırgızistan", nationality: "Kyrgyz", nationalityAr: "قيرغيزي", nationalityTr: "Kırgız" },
  { code: "LA", name: "Laos", nameAr: "لاوس", nameTr: "Laos", nationality: "Lao", nationalityAr: "لاوسي", nationalityTr: "Laoslu" },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", nameTr: "Letonya", nationality: "Latvian", nationalityAr: "لاتفي", nationalityTr: "Letonyalı" },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", nameTr: "Lübnan", nationality: "Lebanese", nationalityAr: "لبناني", nationalityTr: "Lübnanlı" },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", nameTr: "Lesoto", nationality: "Basotho", nationalityAr: "ليسوتي", nationalityTr: "Lesotolu" },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", nameTr: "Liberya", nationality: "Liberian", nationalityAr: "ليبيري", nationalityTr: "Liberyalı" },
  { code: "LY", name: "Libya", nameAr: "ليبيا", nameTr: "Libya", nationality: "Libyan", nationalityAr: "ليبي", nationalityTr: "Libyalı" },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", nameTr: "Lihtenştayn", nationality: "Liechtensteiner", nationalityAr: "ليختنشتايني", nationalityTr: "Lihtenştaynlı" },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", nameTr: "Litvanya", nationality: "Lithuanian", nationalityAr: "ليتواني", nationalityTr: "Litvanyalı" },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", nameTr: "Lüksemburg", nationality: "Luxembourgish", nationalityAr: "لوكسمبورغي", nationalityTr: "Lüksemburglu" },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", nameTr: "Madagaskar", nationality: "Malagasy", nationalityAr: "مدغشقري", nationalityTr: "Madagaskarlı" },
  { code: "MW", name: "Malawi", nameAr: "مالاوي", nameTr: "Malavi", nationality: "Malawian", nationalityAr: "مالاوي", nationalityTr: "Malavili" },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", nameTr: "Malezya", nationality: "Malaysian", nationalityAr: "ماليزي", nationalityTr: "Malezyalı" },
  { code: "MV", name: "Maldives", nameAr: "جزر المالديف", nameTr: "Maldivler", nationality: "Maldivian", nationalityAr: "مالديفي", nationalityTr: "Maldivli" },
  { code: "ML", name: "Mali", nameAr: "مالي", nameTr: "Mali", nationality: "Malian", nationalityAr: "مالي", nationalityTr: "Malili" },
  { code: "MT", name: "Malta", nameAr: "مالطا", nameTr: "Malta", nationality: "Maltese", nationalityAr: "مالطي", nationalityTr: "Maltalı" },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", nameTr: "Marshall Adaları", nationality: "Marshallese", nationalityAr: "مارشالي", nationalityTr: "Marshall Adalı" },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", nameTr: "Moritanya", nationality: "Mauritanian", nationalityAr: "موريتاني", nationalityTr: "Moritanyalı" },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", nameTr: "Mauritius", nationality: "Mauritian", nationalityAr: "موريشيوسي", nationalityTr: "Mauritiuslu" },
  { code: "MX", name: "Mexico", nameAr: "المكسيك", nameTr: "Meksika", nationality: "Mexican", nationalityAr: "مكسيكي", nationalityTr: "Meksikalı" },
  { code: "FM", name: "Micronesia", nameAr: "ميكرونيزيا", nameTr: "Mikronezya", nationality: "Micronesian", nationalityAr: "ميكرونيزي", nationalityTr: "Mikronezyalı" },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", nameTr: "Moldova", nationality: "Moldovan", nationalityAr: "مولدوفي", nationalityTr: "Moldovalı" },
  { code: "MC", name: "Monaco", nameAr: "موناكو", nameTr: "Monako", nationality: "Monégasque", nationalityAr: "موناكوي", nationalityTr: "Monakolı" },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", nameTr: "Moğolistan", nationality: "Mongolian", nationalityAr: "منغولي", nationalityTr: "Moğol" },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", nameTr: "Karadağ", nationality: "Montenegrin", nationalityAr: "جبل أسودي", nationalityTr: "Karadağlı" },
  { code: "MA", name: "Morocco", nameAr: "المغرب", nameTr: "Fas", nationality: "Moroccan", nationalityAr: "مغربي", nationalityTr: "Faslı" },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", nameTr: "Mozambik", nationality: "Mozambican", nationalityAr: "موزمبيقي", nationalityTr: "Mozambikli" },
  { code: "MM", name: "Myanmar", nameAr: "ميانمار", nameTr: "Myanmar", nationality: "Burmese", nationalityAr: "ميانماري", nationalityTr: "Myanmarlı" },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", nameTr: "Namibya", nationality: "Namibian", nationalityAr: "ناميبي", nationalityTr: "Namibyalı" },
  { code: "NR", name: "Nauru", nameAr: "ناورو", nameTr: "Nauru", nationality: "Nauruan", nationalityAr: "ناوروي", nationalityTr: "Naurulu" },
  { code: "NP", name: "Nepal", nameAr: "نيبال", nameTr: "Nepal", nationality: "Nepali", nationalityAr: "نيبالي", nationalityTr: "Nepalli" },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", nameTr: "Hollanda", nationality: "Dutch", nationalityAr: "هولندي", nationalityTr: "Hollandalı" },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", nameTr: "Yeni Zelanda", nationality: "New Zealander", nationalityAr: "نيوزيلندي", nationalityTr: "Yeni Zelandalı" },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", nameTr: "Nikaragua", nationality: "Nicaraguan", nationalityAr: "نيكاراغوي", nationalityTr: "Nikaragualı" },
  { code: "NE", name: "Niger", nameAr: "النيجر", nameTr: "Nijer", nationality: "Nigerien", nationalityAr: "نيجري", nationalityTr: "Nijerli" },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", nameTr: "Nijerya", nationality: "Nigerian", nationalityAr: "نيجيري", nationalityTr: "Nijeryalı" },
  { code: "NO", name: "Norway", nameAr: "النرويج", nameTr: "Norveç", nationality: "Norwegian", nationalityAr: "نرويجي", nationalityTr: "Norveçli" },
  { code: "OM", name: "Oman", nameAr: "عُمان", nameTr: "Umman", nationality: "Omani", nationalityAr: "عُماني", nationalityTr: "Ummanlı" },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", nameTr: "Pakistan", nationality: "Pakistani", nationalityAr: "باكستاني", nationalityTr: "Pakistanlı" },
  { code: "PW", name: "Palau", nameAr: "بالاو", nameTr: "Palau", nationality: "Palauan", nationalityAr: "بالاوي", nationalityTr: "Palaulı" },
  { code: "PA", name: "Panama", nameAr: "بنما", nameTr: "Panama", nationality: "Panamanian", nationalityAr: "بنمي", nationalityTr: "Panamalı" },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", nameTr: "Papua Yeni Gine", nationality: "Papua New Guinean", nationalityAr: "بابواني", nationalityTr: "Papua Yeni Gineli" },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", nameTr: "Paraguay", nationality: "Paraguayan", nationalityAr: "باراغوياني", nationalityTr: "Paraguaylı" },
  { code: "PE", name: "Peru", nameAr: "بيرو", nameTr: "Peru", nationality: "Peruvian", nationalityAr: "بيروي", nationalityTr: "Perulu" },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", nameTr: "Filipinler", nationality: "Filipino", nationalityAr: "فلبيني", nationalityTr: "Filipinli" },
  { code: "PL", name: "Poland", nameAr: "بولندا", nameTr: "Polonya", nationality: "Polish", nationalityAr: "بولندي", nationalityTr: "Polonyalı" },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", nameTr: "Portekiz", nationality: "Portuguese", nationalityAr: "برتغالي", nationalityTr: "Portekizli" },
  { code: "QA", name: "Qatar", nameAr: "قطر", nameTr: "Katar", nationality: "Qatari", nationalityAr: "قطري", nationalityTr: "Katarlı" },
  { code: "RO", name: "Romania", nameAr: "رومانيا", nameTr: "Romanya", nationality: "Romanian", nationalityAr: "روماني", nationalityTr: "Romanyalı" },
  { code: "RU", name: "Russia", nameAr: "روسيا", nameTr: "Rusya", nationality: "Russian", nationalityAr: "روسي", nationalityTr: "Rus" },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", nameTr: "Ruanda", nationality: "Rwandan", nationalityAr: "رواندي", nationalityTr: "Ruandalı" },
  { code: "KN", name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", nameTr: "Saint Kitts ve Nevis", nationality: "Kittitian", nationalityAr: "كيتسي", nationalityTr: "Saint Kittslı" },
  { code: "LC", name: "Saint Lucia", nameAr: "سانت لوسيا", nameTr: "Saint Lucia", nationality: "Saint Lucian", nationalityAr: "لوسياوي", nationalityTr: "Saint Lucialı" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت وجزر غرينادين", nameTr: "Saint Vincent ve Grenadinler", nationality: "Vincentian", nationalityAr: "فنسنتي", nationalityTr: "Saint Vincentlı" },
  { code: "WS", name: "Samoa", nameAr: "ساموا", nameTr: "Samoa", nationality: "Samoan", nationalityAr: "ساموي", nationalityTr: "Samoalı" },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", nameTr: "San Marino", nationality: "Sammarinese", nationalityAr: "سان مارينوي", nationalityTr: "San Marinolu" },
  { code: "ST", name: "São Tomé and Príncipe", nameAr: "ساو تومي وبرينسيبي", nameTr: "São Tomé ve Príncipe", nationality: "São Toméan", nationalityAr: "ساو تومي", nationalityTr: "São Tomélı" },
  { code: "SA", name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", nameTr: "Suudi Arabistan", nationality: "Saudi", nationalityAr: "سعودي", nationalityTr: "Suudi" },
  { code: "SN", name: "Senegal", nameAr: "السنغال", nameTr: "Senegal", nationality: "Senegalese", nationalityAr: "سنغالي", nationalityTr: "Senegalli" },
  { code: "RS", name: "Serbia", nameAr: "صربيا", nameTr: "Sırbistan", nationality: "Serbian", nationalityAr: "صربي", nationalityTr: "Sırp" },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", nameTr: "Seyşeller", nationality: "Seychellois", nationalityAr: "سيشلي", nationalityTr: "Seyşelli" },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", nameTr: "Sierra Leone", nationality: "Sierra Leonean", nationalityAr: "سيراليوني", nationalityTr: "Sierra Leoneli" },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", nameTr: "Singapur", nationality: "Singaporean", nationalityAr: "سنغافوري", nationalityTr: "Singapurlu" },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", nameTr: "Slovakya", nationality: "Slovak", nationalityAr: "سلوفاكي", nationalityTr: "Slovak" },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", nameTr: "Slovenya", nationality: "Slovenian", nationalityAr: "سلوفيني", nationalityTr: "Sloven" },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", nameTr: "Solomon Adaları", nationality: "Solomon Islander", nationalityAr: "سليماني", nationalityTr: "Solomon Adalı" },
  { code: "SO", name: "Somalia", nameAr: "الصومال", nameTr: "Somali", nationality: "Somali", nationalityAr: "صومالي", nationalityTr: "Somalili" },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", nameTr: "Güney Afrika", nationality: "South African", nationalityAr: "جنوب أفريقي", nationalityTr: "Güney Afrikalı" },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", nameTr: "Güney Sudan", nationality: "South Sudanese", nationalityAr: "جنوب سوداني", nationalityTr: "Güney Sudanlı" },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", nameTr: "İspanya", nationality: "Spanish", nationalityAr: "إسباني", nationalityTr: "İspanyol" },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", nameTr: "Sri Lanka", nationality: "Sri Lankan", nationalityAr: "سريلانكي", nationalityTr: "Sri Lankalı" },
  { code: "SD", name: "Sudan", nameAr: "السودان", nameTr: "Sudan", nationality: "Sudanese", nationalityAr: "سوداني", nationalityTr: "Sudanlı" },
  { code: "SR", name: "Suriname", nameAr: "سورينام", nameTr: "Surinam", nationality: "Surinamese", nationalityAr: "سوريناني", nationalityTr: "Surinamlı" },
  { code: "SE", name: "Sweden", nameAr: "السويد", nameTr: "İsveç", nationality: "Swedish", nationalityAr: "سويدي", nationalityTr: "İsveçli" },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", nameTr: "İsviçre", nationality: "Swiss", nationalityAr: "سويسري", nationalityTr: "İsviçreli" },
  { code: "SY", name: "Syria", nameAr: "سوريا", nameTr: "Suriye", nationality: "Syrian", nationalityAr: "سوري", nationalityTr: "Suriyeli" },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", nameTr: "Tayvan", nationality: "Taiwanese", nationalityAr: "تايواني", nationalityTr: "Tayvanlı" },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", nameTr: "Tacikistan", nationality: "Tajik", nationalityAr: "طاجيكي", nationalityTr: "Tacik" },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", nameTr: "Tanzanya", nationality: "Tanzanian", nationalityAr: "تنزاني", nationalityTr: "Tanzanyalı" },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", nameTr: "Tayland", nationality: "Thai", nationalityAr: "تايلاندي", nationalityTr: "Taylandlı" },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية", nameTr: "Doğu Timor", nationality: "Timorese", nationalityAr: "تيموري", nationalityTr: "Doğu Timorlu" },
  { code: "TG", name: "Togo", nameAr: "توغو", nameTr: "Togo", nationality: "Togolese", nationalityAr: "توغولي", nationalityTr: "Togolu" },
  { code: "TO", name: "Tonga", nameAr: "تونغا", nameTr: "Tonga", nationality: "Tongan", nationalityAr: "تونغي", nationalityTr: "Tongalı" },
  { code: "TT", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", nameTr: "Trinidad ve Tobago", nationality: "Trinidadian", nationalityAr: "ترينيدادي", nationalityTr: "Trinidadlı" },
  { code: "TN", name: "Tunisia", nameAr: "تونس", nameTr: "Tunus", nationality: "Tunisian", nationalityAr: "تونسي", nationalityTr: "Tunuslu" },
  { code: "TR", name: "Turkey", nameAr: "تركيا", nameTr: "Türkiye", nationality: "Turkish", nationalityAr: "تركي", nationalityTr: "Türk" },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", nameTr: "Türkmenistan", nationality: "Turkmen", nationalityAr: "تركماني", nationalityTr: "Türkmen" },
  { code: "TV", name: "Tuvalu", nameAr: "توفالو", nameTr: "Tuvalu", nationality: "Tuvaluan", nationalityAr: "توفالوي", nationalityTr: "Tuvalulu" },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", nameTr: "Uganda", nationality: "Ugandan", nationalityAr: "أوغندي", nationalityTr: "Ugandali" },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", nameTr: "Ukrayna", nationality: "Ukrainian", nationalityAr: "أوكراني", nationalityTr: "Ukraynalı" },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", nameTr: "Birleşik Arap Emirlikleri", nationality: "Emirati", nationalityAr: "إماراتي", nationalityTr: "Emiratili" },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", nameTr: "Birleşik Krallık", nationality: "British", nationalityAr: "بريطاني", nationalityTr: "İngiliz" },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة الأمريكية", nameTr: "Amerika Birleşik Devletleri", nationality: "American", nationalityAr: "أمريكي", nationalityTr: "Amerikalı" },
  { code: "UY", name: "Uruguay", nameAr: "أوروغواي", nameTr: "Uruguay", nationality: "Uruguayan", nationalityAr: "أوروغوياني", nationalityTr: "Uruguaylı" },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", nameTr: "Özbekistan", nationality: "Uzbek", nationalityAr: "أوزبكي", nationalityTr: "Özbek" },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", nameTr: "Vanuatu", nationality: "Ni-Vanuatu", nationalityAr: "فانواتوي", nationalityTr: "Vanuatulu" },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", nameTr: "Venezuela", nationality: "Venezuelan", nationalityAr: "فنزويلي", nationalityTr: "Venezuelalı" },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", nameTr: "Vietnam", nationality: "Vietnamese", nationalityAr: "فيتنامي", nationalityTr: "Vietnamlı" },
  { code: "YE", name: "Yemen", nameAr: "اليمن", nameTr: "Yemen", nationality: "Yemeni", nationalityAr: "يمني", nationalityTr: "Yemenli" },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", nameTr: "Zambiya", nationality: "Zambian", nationalityAr: "زامبي", nationalityTr: "Zambiyalı" },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", nameTr: "Zimbabve", nationality: "Zimbabwean", nationalityAr: "زيمبابوي", nationalityTr: "Zimbabveli" },
];

export type Country = (typeof COUNTRIES)[number];

// Helper to get localized country name
export function getCountryName(code: string, lang: "en" | "ar" | "tr" = "en"): string {
  const c = COUNTRIES.find((x) => x.code === code);
  if (!c) return code;
  if (lang === "ar") return c.nameAr;
  if (lang === "tr") return c.nameTr;
  return c.name;
}

// Helper to get localized nationality
export function getNationalityLabel(nationality: string, lang: "en" | "ar" | "tr" = "en"): string {
  const c = COUNTRIES.find((x) => x.nationality === nationality);
  if (!c) return nationality;
  if (lang === "ar") return c.nationalityAr;
  if (lang === "tr") return c.nationalityTr;
  return c.nationality;
}

export const NATIONALITIES = COUNTRIES.map(c => ({
  value: c.nationality,
  label: c.nationality,
  labelAr: c.nationalityAr,
  labelTr: c.nationalityTr,
  code: c.code,
})).sort((a, b) => a.label.localeCompare(b.label));

export const COUNTRY_NAMES = COUNTRIES.map(c => ({
  value: c.name,
  label: c.name,
  labelAr: c.nameAr,
  labelTr: c.nameTr,
  code: c.code,
})).sort((a, b) => a.label.localeCompare(b.label));
