CREATE TABLE `pending_lab_tests` (
  `id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `rawName` varchar(512) NOT NULL,
  `source` enum('patient_entry','pdf_import') NOT NULL DEFAULT 'patient_entry',
  `patientId` int,
  `suggestedCanonicalName` varchar(256),
  `suggestedDisplayName` varchar(512),
  `suggestedAbbreviation` varchar(64),
  `suggestedResultType` varchar(64),
  `suggestedCategory` varchar(128),
  `suggestedSpecimen` varchar(128),
  `suggestedUnits` varchar(256),
  `aiConfidence` enum('high','medium','low') DEFAULT 'medium',
  `possibleMatchId` int,
  `possibleMatchName` varchar(256),
  `possibleMatchScore` int,
  `status` enum('pending','approved','rejected','merged') NOT NULL DEFAULT 'pending',
  `mergedIntoDictionaryId` int,
  `rejectionReason` varchar(512),
  `submittedById` int NOT NULL,
  `reviewedById` int,
  `reviewedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP
);
