CREATE TABLE `ai_usage_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `logicalRequestId` varchar(64) NOT NULL,
  `workloadId` varchar(96) NOT NULL,
  `configurationScope` varchar(96) NOT NULL DEFAULT 'platform_default',
  `status` enum('started','succeeded','failed') NOT NULL DEFAULT 'started',
  `attemptCount` int NOT NULL DEFAULT 0,
  `fallbackUsed` boolean NOT NULL DEFAULT false,
  `totalLatencyMs` int NULL,
  `inputTokens` bigint NULL,
  `outputTokens` bigint NULL,
  `cachedTokens` bigint NULL,
  `totalTokens` bigint NULL,
  `nonTokenUnit` varchar(48) NULL,
  `nonTokenQuantity` decimal(14,3) NULL,
  `estimatedCost` decimal(18,8) NULL,
  `providerReportedCost` decimal(18,8) NULL,
  `costCurrency` varchar(8) NULL,
  `failureCategory` varchar(64) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` timestamp NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ai_usage_requests_logical_request_id_unique` (`logicalRequestId`),
  KEY `idx_ai_usage_requests_workload_created` (`workloadId`, `createdAt`),
  KEY `idx_ai_usage_requests_status_created` (`status`, `createdAt`)
);

CREATE TABLE `ai_usage_attempts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `attemptId` varchar(64) NOT NULL,
  `logicalRequestId` varchar(64) NOT NULL,
  `workloadId` varchar(96) NOT NULL,
  `provider` varchar(64) NOT NULL,
  `model` varchar(160) NOT NULL,
  `attemptNumber` int NOT NULL,
  `status` enum('started','succeeded','failed') NOT NULL DEFAULT 'started',
  `latencyMs` int NULL,
  `inputTokens` bigint NULL,
  `outputTokens` bigint NULL,
  `cachedTokens` bigint NULL,
  `totalTokens` bigint NULL,
  `nonTokenUnit` varchar(48) NULL,
  `nonTokenQuantity` decimal(14,3) NULL,
  `providerUsageAvailable` boolean NOT NULL DEFAULT false,
  `failureCategory` varchar(64) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` timestamp NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ai_usage_attempts_attempt_id_unique` (`attemptId`),
  KEY `idx_ai_usage_attempts_logical_request` (`logicalRequestId`, `attemptNumber`),
  KEY `idx_ai_usage_attempts_provider_model_created` (`provider`, `model`, `createdAt`),
  KEY `idx_ai_usage_attempts_workload_created` (`workloadId`, `createdAt`)
);
