-- WhatsApp WU-05 normalized provider evidence.
-- Additive only: preserves 0096 raw batches/events, contains no identity links,
-- no Conversation/Patient/Lead authority, and performs no backfill.

CREATE TABLE `whatsapp_normalized_messages` (
  `id` int AUTO_INCREMENT NOT NULL,
  `sourceEventId` int NOT NULL,
  `connectionId` int,
  `connectionRoute` enum('legacy_env','persisted'),
  `provider` enum('meta') NOT NULL DEFAULT 'meta',
  `wabaId` varchar(128),
  `providerPhoneNumberId` varchar(128),
  `providerMessageId` varchar(128),
  `providerItemKey` varchar(128) NOT NULL,
  `providerSenderId` varchar(128),
  `providerRecipientId` varchar(128),
  `providerTimestamp` timestamp NULL,
  `providerDirection` enum('inbound','outbound_echo','unknown') NOT NULL,
  `messageType` varchar(64) NOT NULL,
  `textBody` text,
  `normalizedContent` json,
  `normalizationVersion` varchar(32) NOT NULL,
  `normalizationState` enum('normalized','quarantined') NOT NULL,
  `failureCategory` varchar(64),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `whatsapp_normalized_messages_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `whatsapp_normalized_messages_provider_item_uq` UNIQUE(`provider`,`providerItemKey`),
  INDEX `whatsapp_normalized_messages_source_event_ix` (`sourceEventId`),
  INDEX `whatsapp_normalized_messages_provider_message_ix` (`provider`,`providerMessageId`),
  INDEX `whatsapp_normalized_messages_connection_time_ix` (`connectionId`,`providerTimestamp`)
);

CREATE TABLE `whatsapp_normalized_statuses` (
  `id` int AUTO_INCREMENT NOT NULL,
  `sourceEventId` int NOT NULL,
  `connectionId` int,
  `connectionRoute` enum('legacy_env','persisted'),
  `provider` enum('meta') NOT NULL DEFAULT 'meta',
  `wabaId` varchar(128),
  `providerPhoneNumberId` varchar(128),
  `providerStatusId` varchar(128),
  `providerStatusKey` varchar(128) NOT NULL,
  `providerMessageId` varchar(128),
  `providerRecipientId` varchar(128),
  `providerTimestamp` timestamp NULL,
  `statusValue` varchar(64) NOT NULL,
  `errorCode` varchar(64),
  `errorTitle` varchar(256),
  `normalizationVersion` varchar(32) NOT NULL,
  `normalizationState` enum('normalized','quarantined') NOT NULL,
  `failureCategory` varchar(64),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `whatsapp_normalized_statuses_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `whatsapp_normalized_statuses_provider_key_uq` UNIQUE(`provider`,`providerStatusKey`),
  INDEX `whatsapp_normalized_statuses_source_event_ix` (`sourceEventId`),
  INDEX `whatsapp_normalized_statuses_provider_message_ix` (`provider`,`providerMessageId`),
  INDEX `whatsapp_normalized_statuses_connection_time_ix` (`connectionId`,`providerTimestamp`)
);

CREATE TABLE `whatsapp_normalized_media` (
  `id` int AUTO_INCREMENT NOT NULL,
  `sourceEventId` int NOT NULL,
  `connectionId` int,
  `connectionRoute` enum('legacy_env','persisted'),
  `provider` enum('meta') NOT NULL DEFAULT 'meta',
  `wabaId` varchar(128),
  `providerPhoneNumberId` varchar(128),
  `sourceMessageItemKey` varchar(128) NOT NULL,
  `providerMediaItemKey` varchar(128) NOT NULL,
  `providerMediaId` varchar(128),
  `mediaType` varchar(64) NOT NULL,
  `mimeType` varchar(128),
  `sha256` varchar(128),
  `filename` varchar(512),
  `caption` text,
  `mediaState` enum('metadata_only','quarantined') NOT NULL,
  `failureCategory` varchar(64),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `whatsapp_normalized_media_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `whatsapp_normalized_media_provider_item_uq` UNIQUE(`provider`,`providerMediaItemKey`),
  INDEX `whatsapp_normalized_media_source_event_ix` (`sourceEventId`),
  INDEX `whatsapp_normalized_media_provider_id_ix` (`provider`,`providerMediaId`)
);
